body:
  - type: markdown
    attributes:
      value: |
        ここにマークダウンで説明文などを書いてください。
        改行も反映されます。
        - 箇条書きもできます。
        - 見出しもできます。
          # 見出し1
          ## 見出し2
          ### 見出し3
        - 画像も表示できます。
        <img width="1822" height="2000" alt="PCA_character_顔_カラー10" src="https://github.com/user-attachments/assets/8e5f355b-f98d-4a62-8746-e7b598b7097f" />
        - リンクも貼れます。
          [Google](https://www.google.com)
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: まず何について共有するのかを簡潔に書いてください。
      placeholder: 出張時の手続きや、チーム内でよく使うルールなど
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: 内容
      description: 後から読む人が分かるように、背景や詳細を書いてください。
      placeholder: |
        - 何の情報か  
        - どういう場面で役立つか  
        - 補足事項  
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: 関連リンク・参考情報
      description: 参考になる文書やリンクがあれば記載してください。
      placeholder: SharePoint、Slackなど
