title: "[質問] "
body:
  - type: markdown
    attributes:
      value: |
        upload の確認用です

  - type: input
    id: summary
    attributes:
      label: 要約
    validations:
      required: true

  - type: upload
    id: attachments
    attributes:
      label: 添付ファイル
      description: ファイルを添付してください
